name: .NET

on:
  push:
    branches: [ main, develop, feature/*, release/* ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/api/SmartExpenseManagement.sln
    - name: Build
      run: dotnet build --no-restore ./src/api/SmartExpenseManagement.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/api/SmartExpenseManagement.sln
